version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
  server:
    build: ./
    ports:
      - '3005:3005'
    depends_on:
      - posgressDb
